name: Build and Push Docker Image from Autogen Source

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build-and-push-from-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for tag fetch
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/autogen'
          ref: 'refs/heads/main'

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli tree

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Compare tags and build missing
        run: |
          git fetch --tags
          for tag in $(git tag); do
            if ! docker manifest inspect ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:$tag > /dev/null; then
              echo "Building and pushing tag $tag"

              # Checkout specific tag
              git checkout $tag

              # Create Dockerfile
              echo 'FROM python:3.10' > Dockerfile
              echo 'COPY . /autogen' >> Dockerfile
              echo 'WORKDIR /autogen/samples/apps/autogen-studio' >> Dockerfile
              echo 'RUN pip install -e .' >> Dockerfile
              tree .
              echo 'COPY samples/apps/autogen-studio/frontend/public /autogen/samples/apps/autogen-studio/frontend/public' >> Dockerfile
              echo 'ENV AUTOGEN_PORT=8080' >> Dockerfile
              echo 'ENV AUTOGEN_HOST=127.0.0.1' >> Dockerfile
              echo 'ENV AUTOGEN_WORKERS=1' >> Dockerfile
              echo 'RUN mkdir -p /tmp/data/db /tmp/data/user' >> Dockerfile
              echo 'RUN mkdir -p /autogen/samples/apps/autogen-studio/autogenstudio/web/files/user' >> Dockerfile
              echo 'RUN ln -s /data/database.sqlite /autogen/samples/apps/autogen-studio/autogenstudio/web/database.sqlite' >> Dockerfile
              echo 'RUN ln -s /data/user /autogen/samples/apps/autogen-studio/autogenstudio/web/files/user' >> Dockerfile
              echo 'CMD ["/bin/sh", "-c", "autogenstudio ui --host $AUTOGEN_HOST --port $AUTOGEN_PORT --workers $AUTOGEN_WORKERS"]' >> Dockerfile

              # Run Docker build and push commands
              docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:$tag .
              docker push ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:$tag

            else
              echo "Tag $tag already exists on Docker Hub, skipping..."
            fi
          done

