name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build Docker Image
      run: docker build -f samples/dockers/Dockerfile.base -t daxiongmao87/autogen_studio https://github.com/microsoft/autogen.git#main

    - name: Push Docker Image to Docker Hub
      run: docker push your-dockerhub-username/autogen_studio:latest
