name: Build and Push Docker Image from Autogen Source

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  build-and-push-from-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout for tag fetch
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/autogen'
          ref: 'refs/heads/main'

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce-cli

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Compare tags and build missing
        run: |
          git fetch --tags
          for tag in $(git tag); do
            if ! docker manifest inspect ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:$tag > /dev/null; then
              echo "Building and pushing tag $tag"

              # Checkout specific tag
              git checkout $tag

              # Replace the following commands with your Docker build instructions
              docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:$tag .
              docker push ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:$tag

            else
              echo "Tag $tag already exists on Docker Hub, skipping..."
            fi
          done
