name: Build and Push Docker Image from Autogen Source

on:
  release:
    types: [published]
    repos:
      - microsoft/autogen
  workflow_dispatch:

jobs:
  build-and-push-from-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Autogen Studio code
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/autogen'
          # You may not need to specify ref if you're just getting the latest tag

      - name: Fetch latest tag from microsoft/autogen
        id: latest_tag
        run: |
          git fetch --tags
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "LATEST_TAG=${LATEST_TAG}" >> $GITHUB_ENV
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'


      - name: Install Python dependencies
        run: pip install -e .

      - name: Install and Build Frontend
        run: |
          npm install -g gatsby-cli
          npm install --global yarn
          cd samples/apps/autogen-studio/frontend
          yarn install
          yarn build

      - name: Create Dockerfile
        run: |
          echo 'FROM python:3.10' > Dockerfile
          echo 'ENV AUTOGENUI_PORT=8080' >> Dockerfile
          echo 'COPY . /autogen' >> Dockerfile
          echo 'WORKDIR /autogen/samples/apps/autogen-studio' >> Dockerfile
          echo 'RUN pip install -e .' >> Dockerfile
          echo 'COPY ./samples/apps/autogen-studio/frontend/public /autogen/samples/apps/autogen-studio/frontend/public' >> Dockerfile
          echo 'CMD ["/bin/sh" "-c python manage.py runserver 0.0.0.0:$AUTOGENUI_PORT"]' >> Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:${{ env.LATEST_TAG }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/autogen_studio_ui:latest
      
